services:
  frontend:
    container_name: frontend
    ports:
      - "${VITE_APP_PORT:-5173}:${VITE_APP_PORT:-5173}"
    build:
      context: ./react
      dockerfile: Dockerfile
      target: ${VITE_BUILD_STAGE:-development}
    working_dir: /app
    environment:
      - VITE_PORT=${VITE_PORT}
      - VITE_BACKEND_PORT=${VITE_BACKEND_PORT}
      - VITE_BUILD_STAGE=${VITE_BUILD_STAGE}
      - VITE_HOST=${VITE_HOST}
      - VITE_UPLOAD_PASSCODE=${VITE_UPLOAD_PASSCODE}
    volumes:
      - ./react:/app
      - /app/node_modules
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - personal-website-network

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: ${VITE_BUILD_STAGE:-development}
    ports:
      - "${BACKEND_PORT:-8080}:${BACKEND_PORT:-8080}"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - personal-website-network

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:${DB_PORT:-5432}"
    networks:
      - personal-website-network

volumes:
  postgres-data:

networks:
  personal-website-network:
    driver: bridge
