services:
  frontend:
    container_name: frontend
    ports:
      - "${VITE_APP_PORT:-5137}:${VITE_APP_PORT:-5137}"
    build:
      context: ./react
      dockerfile: Dockerfile
      target: ${BUILD_STAGE}
    working_dir: /app
    environment:
      - VITE_APP_PORT=${VITE_APP_PORT}
      - BACKEND_PORT=${BACKEND_PORT}
      - BUILD_STAGE=${BUILD_STAGE}
      - HOST=${HOST}
      - VITE_RESUME_UPLOAD_PASSCODE=${VITE_RESUME_UPLOAD_PASSCODE}
    volumes:
      - ./react:/app
      - /app/node_modules
    networks:
      - personal-website-network

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT:-8080}:${BACKEND_PORT:-8080}"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - postgres
    networks:
      - personal-website-network

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:${DB_PORT:-5432}"
    networks:
      - personal-website-network

volumes:
  postgres-data:

networks:
  personal-website-network:
    driver: bridge
