root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/server ."
bin = "tmp/server"
full_bin = "tmp/server"
delay = 1000 # ms
exclude_dir = ["tmp", "vendor"]
include_ext = ["go", "tpl", "tmpl", "html"]

[log]
time = true

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"
